diet_list = [
  [ "Average", "Most omnivorous Americans consume less than ideal amounts of certain nutrients needed for a healthy diet. A large percentage of people fall short of the average requirements of many nutrients, like  vitamin D, E, and A , along with calcium and magnesium. Almost half fall short of vitamin C, that you can get in fruits and vegetables. omnivores may have higher rates of cancer, diabetes, and heart disease than vegans and vegetarians. An omnivorous diet also appears to increase the risk of abdominal fat, higher BMI, obesity, unhealthy stools, and accelerated aging.",  "An Average American’s diet has a footprint of around 2.5 tons of CO2 emitted per person each year. In the average diet animal products make up 60% of emissions despite accounting for just a quarter of food energy." ],
  [ "Meat Lover", "Meat is a good source of protein, vitamins and minerals in your diet. Red meat provides us with iron, and meat is also one of the main sources of vitamin B12. However, people who eat a lot of animal protein may be more likely to have excessive fat in their livers and a higher risk of liver disease, as meat is very high in saturated fat, cholesterol and sodium.
Meat based diet eliminates highly nutritious foods like fruits, vegetables, legumes, and whole grains, all of which contain beneficial vitamins and minerals.
", "The estimated emissions from a no beef diet is 3.3 tons of CO2 emitted. This includes food that is eaten, wasted by consumers and lost in the supply chain. For the Meat Lover beef consumption causes almost half of emissions from just a tenth of food energy. " ],
  [ "No Beef", "The pollotarian diet has several benefits. It is a great way for meat lovers to transition into giving up red meat without going completely vegetarian. This helps balance the body’s cholesterol levels, decrease the risk of heart disease and type 2 diabetes, and lower the chances of colon cancer. Also, this diet is great for weight loss, because poultry tends to be lesser fatty and lower on the calories, while also filling up your stomach thanks to its fibre content. However, some possible nutrient deficiencies to be aware of when following a pollotarian diet include: iron, zinc, vitamin B12, calcium and  omega-3 fatty acids deficiencies.", "The estimated emissions from a no beef/pollotarian diet is 1.9 tons of CO2 emitted. This includes food that is eaten, wasted by consumers and lost in the supply chain." ],
  [ "Vegetarian", "A vegetarian diet is associated with many health benefits because of its higher content of fiber, folic acid, vitamins C and E, potassium, magnesium, and many phytochemicals and a fat content that is more unsaturated. While some vegetarian diets may be low in certain nutrients, such as calcium and vitamin B-12, this can be remedied by appropriate planning. Compared to nonvegetarian diets, vegetarian diets can provide protection against many chronic diseases, such as heart disease, hypertension, type 2 diabetes, obesity, and some cancers.", "The estimated emissions from food that is eaten, wasted by consumers and lost in the supply chain: 1.7 tons of CO2 emitted." ],
  [ "Vegan", " Studies have shown that a plant-based diet is the best for health and longevity. Vegan diets are naturally free of cholesterol and are generally low in fat. These diets are therefore often followed to reduce the risk of major chronic diseases, such as heart disease and cancer .Compared with other vegetarian diets, vegan diets tend to contain less saturated fat and cholesterol and more dietary fiber However, some studies have shown that calcium, and vitamin B12 intake is lower when following this eating style. In addition, vegan diets may also be low in iron, iodine, and vitamin D. Vegans might also be at risk for an essential omega-3 fatty acid deficiency.", "The estimated emissions from a no beef/pollotarian diet is 1.5 tons of CO2 emitted. This includes food that is eaten, wasted by consumers and lost in the supply chain."],
]

diet_list.each do |diet, nutrition, c02|
  Diet.create( diet_type: diet, nutrition: nutrition, environmental_impact: c02 )
end

puts("Created #{Diet.count} diets")
